# Generated by Django 3.2.5 on 2021-07-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='shoe-thumbnail/')),
            ],
            options={
                'ordering': ['-dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='ShoeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, default='shoe-thumbnail/default.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(fields=('value',), name='sizeValue'),
        ),
        migrations.AddField(
            model_name='shoeitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color'),
        ),
        migrations.AddField(
            model_name='shoeitem',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shoe'),
        ),
        migrations.AddField(
            model_name='shoeitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('name',), name='colorName'),
        ),
        migrations.AlterUniqueTogether(
            name='shoeitem',
            unique_together={('shoe', 'color', 'size')},
        ),
        migrations.AddConstraint(
            model_name='shoe',
            constraint=models.UniqueConstraint(fields=('name',), name='shoeName'),
        ),
    ]
