# Generated by Django 3.2.5 on 2021-07-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeitem',
            name='picture',
            field=models.ImageField(blank=True, default='shoe-thumbnail/default.png', null=True, upload_to='shoes/'),
        ),
    ]
