# Generated by Django 3.2.5 on 2021-07-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_shoeitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeitem',
            name='picture',
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='shoe-thumbnail/default.png', null=True, upload_to='shoes/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shoe')),
            ],
            options={
                'unique_together': {('shoe', 'color')},
            },
        ),
    ]
