# Generated by Django 3.2.5 on 2021-07-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210719_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order'),
        ),
    ]
