# Generated by Django 3.2.5 on 2021-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_purchaseitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
