# Generated by Django 3.2.5 on 2022-05-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='product.order'),
        ),
    ]
